# Generated by Django 5.2.7 on 2025-11-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cerveza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('pais_origen', models.CharField(max_length=50)),
                ('graduacion_alcoholica', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
